### ISSUE TITLE
Chapter 8. Building a face recognition application.

### ISSUE THREAD

**Issue by zoldaten** [PacktPublishing/Raspberry-Pi-3-Cookbook-for-Python-Programmers-Third-Edition#1]
There was a problem with python3.
So to start code working should be replaced:
`
face_recognizer = cv2.createLBPHFaceRecognizer()
`
with:
`
face_recognizer = cv2.face.LBPHFaceRecognizer_create()
`

**Comment by ManikandanKurup-Packt** [comment]
Hi @zoldaten,
I think it's probably a version issue but thank you for letting us know.  :)
